#!/usr/bin/env bash

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"

/usr/bin/env ruby ./rbsh.rb
while [[ $? -eq 2 ]]
do
  [[ -s "$HOME/.rbsh_bash_command" ]] && . "$HOME/.rbsh_bash_command" && rm "$HOME/.rbsh_bash_command"
  /usr/bin/env ruby ./rbsh.rb "$rbsh_cmd"
done